name: Update
on:
  schedule:
    - cron: "4 23 * * 0"
  push:
    branches:
      - main

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
         token: '${{ github.token }}'
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
      - name: Update
        run: |
          rm -fr * .git .github
          spn_version=$(date '+%Y.%-m.%-d')
          wget -q https://github.com/ycycxz/spn/raw/main/spn
          check_sha256=$(sha256sum ./spn | cut -d " " -f1 )
          echo spn $check_sha256
          echo ====================
          rm -f ./spn

          mkdir -p ./spn/tools

          #chocolateyinstall.ps1

          cat <<EOF > ./spn/tools/chocolateyinstall.ps1
          \$ErrorActionPreference = 'Stop'
          \$DesktopPath = [Environment]::GetFolderPath("Desktop")
          \$toolsDir   = "\$(Get-ToolsLocation)\\\$env:ChocolateyPackageName\\\$env:ChocolateyPackageName.exe"
          \$url64      = 'https://cdn.jsdelivr.net/gh/ycycxz/spn@main/spn' 
          \$checksum64 = "$check_sha256"
          Get-ChocolateyWebFile \$packageName \$toolsDir \$url64 -checksum64 \$checksum64
          Install-ChocolateyShortcut -ShortcutFilePath "\$DesktopPath\SPN.lnk" -TargetPath "\$(Get-ToolsLocation)\\\$env:ChocolateyPackageName\\\$env:ChocolateyPackageName.exe" -WorkingDirectory "\$(Get-ToolsLocation)\\\$env:ChocolateyPackageName\" -RunAsAdmin -PinToTaskbar
          EOF

          cat ./spn/tools/chocolateyinstall.ps1

          #chocolateybeforemodify.ps1
          cat <<EOF > ./spn/tools/chocolateybeforemodify.ps1
          \$ErrorActionPreference = 'Stop'

          Get-Process -Name 'spn' -ErrorAction SilentlyContinue | Stop-Process
          Get-Process -Name 'sing-box' -ErrorAction SilentlyContinue | Stop-Process
          EOF

          cat ./spn/tools/chocolateybeforemodify.ps1
          
          #chocolateyUninstall.ps1
          cat <<EOF > ./spn/tools/chocolateyUninstall.ps1
          \$ErrorActionPreference = 'Stop'
          \$DesktopPath = [Environment]::GetFolderPath("Desktop")
          Remove-Item -Recurse "\$(Get-ToolsLocation)\\\$env:ChocolateyPackageName" -Force
          Remove-Item "\$DesktopPath\SPN.lnk"
          EOF

          cat ./spn/tools/chocolateyUninstall.ps1

          #spn.nuspec
          cat <<EOF > ./spn/spn.nuspec
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
            <metadata>
              <id>spn</id>
              <version>2024.8.5</version>
              <packageSourceUrl>https://github.com/ycycxz/choco-spn</packageSourceUrl>
              <owners>YCYCXZ</owners>
              <title>SPN</title>
              <authors>YCYCXZ</authors>
              <projectUrl>https://github.com/ycycxz/spn</projectUrl>
              <iconUrl>https://cdn.jsdelivr.net/gh/ycycxz/spn@main/logo.svg</iconUrl>
              <copyright>2024 YCYCXZ</copyright>
              <licenseUrl>https://github.com/ycycxz/spn/blob/main/LICENSE</licenseUrl>
              <requireLicenseAcceptance>true</requireLicenseAcceptance>
              <projectSourceUrl>https://github.com/ycycxz/spn</projectSourceUrl>
              <docsUrl>https://ultra.ycycxz.com</docsUrl>
              <mailingListUrl>https://ycycxz.com/contact</mailingListUrl>
              <bugTrackerUrl>https://github.com/ycycxz/spn/issues</bugTrackerUrl>
              <tags>SPN</tags>
              <summary>Safing Private Network</summary>
              <description>
          - The Safing Private Network (SPN) Powered by sing-box
          - ![SPN](https://cdn.jsdelivr.net/gh/ycycxz/spn@main/spn.png)
              </description>
              <dependencies>
                <dependency id="sing-box" version="1.10.0" />
              </dependencies>
            </metadata>
            <files>
              <file src="tools\**" target="tools" />
            </files>
          </package>
          EOF

          cat ./spn/spn.nuspec

          mkdir -p .github/workflows
          wget -qO .github/workflows/blank.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/blank.yml
          
          git config --global init.defaultBranch main
          git init
          git add .
          git config user.name "mainians"
          git config user.email "61817665+mainians@users.noreply.github.com"
          git commit -m "${spn_version}"
          git remote add release "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}"
          git push -u release main -f
  Cpack:
    name: Cpack
    needs: Update
    runs-on: windows-latest
    steps:
      - name: Cpack
        run: |
          git clone -b main https://github.com/${{github.repository}} spn
          cd spn/spn
          choco apikey --key ${{secrets.api_key}} --source https://push.chocolatey.org/
          choco pack
          choco push --source https://push.chocolatey.org/ || true
